name: Verify OCI Image
description: Verify an OCI image against a public key using cosign

inputs:
  cosign-version:
    description: "The version of cosign to use"
    required: false
    default: "v2.2.2"
  public-key:
    description: "The location of the public key to verify against"
    default: "https://raw.githubusercontent.com/rsturla/eternal-main/main/files/etc/pki/containers/eternal-linux.pub"
    required: false
  image:
    description: "The image to verify - e.g. ghcr.io/rsturla/eternal-linux/main/silverblue:latest"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Cosign
      uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2
      with:
        cosign-release: ${{ inputs.cosign-version }}

    - name: Verify OCI Image
      shell: bash
      run: |
        cosign verify --key $COSIGN_PUBLIC_KEY $IMAGE
      env:
        IMAGE: ${{ inputs.image }}
        COSIGN_PUBLIC_KEY: ${{ inputs.public-key }}
