name: Rechunk Image

inputs:
  ref:
    description: 'The reference to the image to rechunk'
    required: true
  prev-ref:
    description: 'The reference to the previous image'
    required: false

runs:
  using: 'composite'
  steps:
    - name: List Images
      shell: bash
      run: sudo podman image ls

    - name: Rechunk Image
      id: rechunk
      uses: hhd-dev/rechunk@341e1298e827bc60cfe19d71539ca42d08c89cfe # v1.1.3
      with:
        rechunk: ghcr.io/hhd-dev/rechunk:v1.1.3
        ref: ${{ inputs.ref }}
        skip_compression: false
        prev-ref: ${{ inputs.prev-ref }}

    - name: Load Image
      shell: bash
      run: |
        sudo podman rmi $(sudo podman image ls -qa) --force
        IMAGE=$(sudo podman pull ${{ steps.rechunk.outputs.ref }})
        tags="${{ inputs.tags }}"
        sudo rm -rf ${{ steps.rechunk.outputs.location }}
        sudo podman tag $IMAGE ${{ inputs.ref }}
        sudo podman image ls
