name: Rechunk Image

inputs:
  ref:
    description: 'The reference to the image to rechunk'
    required: true
  prev-ref:
    description: 'The reference to the previous image'
    required: false

outputs:
  ref: 
    description: The reference of the rechunked image
    value: ${{ steps.rechunk.outputs.ref }}
  location: 
    description: The location on the filesystem of the image
    value: ${{ steps.rechunk.outputs.location }}

runs:
  using: 'composite'
  steps:
    - name: Rechunk Image
      id: rechunk
      uses: hhd-dev/rechunk@341e1298e827bc60cfe19d71539ca42d08c89cfe # v1.1.3
      with:
        rechunk: ghcr.io/hhd-dev/rechunk:v1.1.3
        ref: ${{ inputs.ref }}
        skip_compression: false
        prev-ref: ${{ inputs.prev-ref }}
