name: Rechunk Image

inputs:
  ref:
    description: 'The reference to the image to rechunk'
    required: true
  prev-ref:
    description: 'The reference to the previous image'
    required: false
  max-layers:
    description: 'The maximum number of layers to include in an image'
    required: false
    default: 64

runs:
  using: 'composite'
  steps:
    - name: List Images
      shell: bash
      run: sudo podman image ls

    - name: Rechunk Image
      id: rechunk
      uses: hhd-dev/rechunk@5fbe1d3a639615d2548d83bc888360de6267b1a2 # v1.2.4
      with:
        rechunk: ghcr.io/hhd-dev/rechunk:v1.2.3
        ref: ${{ inputs.ref }}
        skip_compression: false
        prev-ref: ${{ inputs.prev-ref }}
        max-layers: ${{ inputs.max-layers }}
        meta: ${{ github.action_path }}/config/meta.yaml

    - name: Load Image
      shell: bash
      run: |
        sudo podman rmi $(sudo podman image ls -qa) --force
        IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
        tags="${{ inputs.tags }}"
        sudo rm -rf ${{ steps.rechunk.outputs.location }}
        podman tag $IMAGE ${{ inputs.ref }}
        podman image ls
