name: Rechunk Image

inputs:
  ref:
    description: 'The reference to the image to rechunk'
    required: true
  prev-ref:
    description: 'The reference to the previous image'
    required: false

runs:
  using: 'composite'
  steps:
    - name: List Images
      shell: bash
      run: sudo podman image ls

    - name: Rechunk Image
      id: rechunk
      uses: hhd-dev/rechunk@ded27feba22df48134eece2c66ba0fca1289ff40 # v1.2.3
      with:
        rechunk: ghcr.io/hhd-dev/rechunk:v1.2.2
        ref: ${{ inputs.ref }}
        skip_compression: false
        prev-ref: ${{ inputs.prev-ref }}

    - name: Load Image
      shell: bash
      run: |
        sudo podman rmi $(sudo podman image ls -qa) --force
        IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
        tags="${{ inputs.tags }}"
        sudo rm -rf ${{ steps.rechunk.outputs.location }}
        podman tag $IMAGE ${{ inputs.ref }}
        podman image ls
