name: Rechunk Image

inputs:
  ref:
    description: 'The reference to the image to rechunk'
    required: true
  prev-ref:
    description: 'The reference to the previous image'
    required: false
  max-layers:
    description: 'The maximum number of layers to include in an image'
    required: false
    default: 64

runs:
  using: 'composite'
  steps:
    - name: List Images
      shell: bash
      run: sudo podman image ls

    - name: Rechunk Image
      id: rechunk
      uses: ublue-os/legacy-rechunk@a925083d9af7cb04b3e2a6e8c01bfa495f38b710 # v1.0.0
      with:
        rechunk: ghcr.io/ublue-os/legacy-rechunk:v1.0.1
        ref: ${{ inputs.ref }}
        skip_compression: false
        prev-ref: ${{ inputs.prev-ref }}
        max-layers: ${{ inputs.max-layers }}
        meta: ${{ github.action_path }}/config/meta.yaml

    - name: Load Image
      shell: bash
      run: |
        sudo podman rmi $(sudo podman image ls -qa) --force
        IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
        tags="${{ inputs.tags }}"
        sudo rm -rf ${{ steps.rechunk.outputs.location }}
        podman tag $IMAGE ${{ inputs.ref }}
        podman image ls
