name: Run pre-commit

inputs:
  pre-commit-args:
    description: 'Additional arguments to pass to pre-commit'
    required: false
    default: '--all-files'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5

    - name: Run pre-commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: ${{ inputs.pre-commit-args }}

    - name: Check for changed files
      shell: bash
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "pre-commit changed files, please run pre-commit locally and commit the changes"
          exit 1
        fi
