name: Scan Image
description: Scan image with ClairV4

inputs:
  image-ref:
    description: 'Image reference'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Save Docker image
      shell: bash
      run: |
        docker save -o ${{ github.sha }} ${{ inputs.image-ref }}

    - name: Scan image
      uses: quay/clair-action@main
      with:
        image-path: ${{ github.sha }}
        format: clair
        output: clair-results.md
        return-code: 1

    - name: Upload results to Job Summary
      if: always()
      shell: bash
      run: |
        cat clair-results.md >> $GITHUB_STEP_SUMMARY
