name: Validate Renovate config

inputs:
  renovate-version:
    description: 'The version of Renovate to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: latest

    - name: Install dependencies
      shell: bash
      env:
        RENOVATE_VERSION: ${{ inputs.renovate-version }}
      run: npm install -g renovate@${RENOVATE_VERSION}

    - name: Validate Renovate config
      shell: bash
      run: renovate-config-validator --strict
