name: Sign OCI Image
description: Signs an OCI image using cosign

inputs:
  cosign-version:
    description: 'The version of cosign to use'
    required: false
    default: 'v2.2.2'
  registry:
    description: 'The registry to push the signed image to'
    required: true
  registry-provider:
    required: false
    default: 'ghcr.io'
  registry-username:
    description: 'The username to authenticate with the registry'
    required: false
    default: ${{ github.actor }}
  registry-password:
    description: 'The password to authenticate with the registry'
    required: false
    default: ${{ github.token }}
  digest:
    description: 'The digest of the image to sign'
    required: true
  private-key:
    description: 'The private key to use for signing'
    required: true
  private-key-passphrase:
    description: 'The passphrase for the private key'
    required: false

runs:
  using: composite
  steps:
    - name: Login to GHCR
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        registry: ${{ inputs.registry-provider }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Setup Cosign
      uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
      with:
        cosign-release: ${{ inputs.cosign-version }}

    - name: Sign OCI Image
      shell: bash
      run: |
        cosign sign -y --key env://COSIGN_PRIVATE_KEY $REGISTRY@$DIGEST
      env:
        REGISTRY: ${{ inputs.registry }}
        DIGEST: ${{ inputs.digest }}
        COSIGN_PRIVATE_KEY: ${{ inputs.private-key }}
        COSIGN_PASSWORD: ${{ inputs.private-key-passphrase }}
