name: Push Image
description: "Pushes a container image to a registry using Podman or Docker"

inputs:
  image-ref:
    description: "The ref of the image"
    required: true
  image-name:
    description: "The name of the image to push"
    required: true
  image-tags:
    description: "The tags to apply to the image"
    required: true
  image-registry:
    description: "The registry to push the image to"
    required: true

outputs:
  registry-path:
    description: "The path to the pushed image in the registry"
    value: ${{ steps.set-outputs.outputs.registry-path }}
  digest:
    description: "The digest of the image in the registry"
    value: ${{ steps.set-outputs.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Push
      id: push-podman
      shell: bash
      env:
        IMAGE_REF: ${{ inputs.image-ref }}
        IMAGE_TAGS: ${{ inputs.image-tags }}
      run: |
        # Convert the tags to an array
        IFS=' ' read -ra TAGS <<< "${IMAGE_TAGS}"
        
        tags=()
        # Push the image with each tag
        for tag in "${TAGS[@]}"; do
          image="${{ inputs.image-registry }}/${{ inputs.image-name }}:${tag}"
          echo "IMAGE=${image}"
          tags+=("${image}")
          podman tag "${IMAGE_REF}" "${image}"
          podman push --digestfile /tmp/digestfile "${image}"
        done

        # Get the digest of the first tag
        digest=$(cat /tmp/digestfile)

        # Set the outputs
        echo "registry-path=${tags[0]}" >> $GITHUB_OUTPUT
        echo "digest=${digest}" >> $GITHUB_OUTPUT

    - name: Set Outputs
      id: set-outputs
      shell: bash
      run: |
        echo "registry-path=${{ steps.push-podman.outputs.registry-path }}" >> $GITHUB_OUTPUT
        echo "digest=${{ steps.push-podman.outputs.digest }}" >> $GITHUB_OUTPUT
