name: Get CoreOS Kernel

inputs:
  coreos-stream:
    description: 'The CoreOS stream to pull the image from'
    required: true
    default: 'stable'
  arch:
    description: 'The image architecture to inspect'
    required: false
    default: 'x86_64'

outputs:
  coreos-repo-version:
    description: 'The Fedora repository version CoreOS sources their kernel from'
    value: ${{ steps.extract-fedora-version.outputs.fedora-version }}
  coreos-kernel-release:
    description: 'The full CoreOS kernel version string'
    value: ${{ steps.extract-kernel-release.outputs.kernel-release }}

runs:
  using: composite
  steps:
    - name: Extract Kernel Release
      id: extract-kernel-release
      shell: bash
      env:
        COREOS_STREAM: ${{ inputs.coreos-stream }}
        ARCH: ${{ inputs.arch }}
      run: |
        podman pull quay.io/skopeo/stable:latest
        KERNEL_RELEASE=$(podman run quay.io/skopeo/stable:latest inspect docker://quay.io/fedora/fedora-coreos:$COREOS_STREAM | jq -r '.Labels["ostree.linux"] | split(".$ARCH")[0]')
        echo "kernel-release=$KERNEL_RELEASE" >> $GITHUB_OUTPUT

    - name: Extract Fedora Repository Version
      shell: bash
      id: extract-fedora-version
      env:
        KERNEL_RELEASE: ${{ steps.extract-kernel-release.outputs.kernel-release }}
      run: |
        FEDORA_VERSION=$(echo $KERNEL_RELEASE | grep -oP 'fc\K[0-9]+')
        echo "fedora-version=$FEDORA_VERSION" >> $GITHUB_OUTPUT
