name: Rechunk Image

inputs:
  image-ref:
    description: "Reference to the image to rechunk"
    required: true
  previous-image-ref:
    description: "Reference to the previous image"
    required: false
  skip-compression:
    description: "Skip compression of the image"
    required: false
    default: "true"
  chunk-count:
    description: "Number of chunks to split the image into"
    required: true
    default: "68"

runs:
  using: "composite"
  steps:
    - name: Transfer Image to Rootful Podman
      shell: bash
      run: |
        podman save ${{ inputs.image-ref }} -o image.tar
        podman image rm ${{ inputs.image-ref }}
        sudo podman load -i image.tar
        rm -f image.tar

    - name: Rechunk Image
      id: rechunk
      uses: hhd-dev/rechunk@v0.8.1
      with:
        ref: ${{ inputs.image-ref }}
        skip_compression: ${{ inputs.skip-compression }}

    - name: Transfer Image to Rootless Podman
      shell: bash
      run: |
        IMAGE=$(podman pull ${{ steps.rechunk.outputs.ref }})
        podman image ls
        sudo podman image ls
        sudo rm -rf ${{ steps.rechunk.outputs.output }}
        podman image tag $IMAGE ${{ inputs.image-ref }}
