name: Security Scan

on:
  workflow_call:
    inputs:
      images:
        description: "A comma-separated list of images to scan.  E.G. '[\"docker.io/library/alpine:3.14.0\", \"docker.io/library/alpine:3.13.6\"]'"
        required: true
        type: string

permissions:
  contents: read
  packages: read

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        env:
          IMAGES: ${{ inputs.images }}
        run: |
          echo "matrix=$IMAGES" >> $GITHUB_OUTPUT

  generate-sbom:
    runs-on: ubuntu-latest
    outputs:
      sbom-file: ${{ steps.generate-sbom.outputs.output-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Image
        shell: bash
        run: |
          docker pull ${{ inputs.image-ref }}

      - name: Generate SBOM
        id: generate-sbom
        uses: ./.github/actions/generate-sbom
        with:
          image-ref: ${{ inputs.image-ref }}
          output-file: sbom.json
          artifact-name: sbom

  scan-sbom:
    runs-on: ubuntu-latest
    needs: generate-sbom
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download SBOM
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: .

      - name: Scan SBOM
        uses: ./.github/actions/scan-sbom
        with:
          sbom-file: ${{ needs.generate-sbom.outputs.sbom-file }}
          artifact-name: scan-results
