name: Build Images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [39]
        fedora-edition: [base, silverblue]
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: eternal-linux/main/${{ matrix.fedora-edition }}
    outputs:
      base-image-full: ${{ steps.generate-image-tags.outputs.primary-name-full }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Generate Image Tags
        uses: ./.github/actions/generate-image-tags
        id: generate-image-tags
        with:
          image-name: ${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_NAME }}
          major-version: ${{ matrix.fedora-version }}
          is-release: ${{ github.event_name != 'pull_request' }}

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ${{ steps.generate-image-tags.outputs.names-full-concat }}
          build-args: |
            FEDORA_VERSION=${{ matrix.fedora-version }}
            FEDORA_EDITION=${{ matrix.fedora-edition }}

      - name: Scan Image
        uses: ./.github/actions/scan-image
        with:
          image-ref: ${{ steps.generate-image-tags.outputs.primary-name-full }}

      - name: Sign Image
        uses: ./.github/actions/sign-image
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          digest: ${{ steps.build.outputs.digest }}
          private-key: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY }}
          private-key-passphrase: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY_PASSPHRASE }}

  build-nvidia:
    runs-on: ubuntu-latest
    needs: build-base
    if: ${{ !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [39]
        fedora-edition: [base, silverblue]
        nvidia-version: [545]
        include:
          - nvidia-version: 545
            nvidia-is-stable: true
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: eternal-linux/main/${{ matrix.fedora-edition }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Generate Image Tags
        uses: ./.github/actions/generate-image-tags
        id: generate-image-tags
        with:
          image-name: ${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_NAME }}
          major-version: ${{ matrix.fedora-version }}
          is-release: ${{ github.event_name != 'pull_request' }}
          nvidia-driver-version: ${{ matrix.nvidia-version }}
          nvidia-driver-is-stable: ${{ matrix.nvidia-is-stable }}

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: .
          file: Containerfile.nvidia
          push: true
          tags: ${{ steps.generate-image-tags.outputs.names-full-concat }}
          build-args: |
            FEDORA_VERSION=${{ matrix.fedora-version }}
            FEDORA_EDITION=${{ matrix.fedora-edition }}
            NVIDIA_VERSION=${{ matrix.nvidia-version }}
            BASE_IMAGE_FULL=${{ needs.build-base.outputs.base-image-full }}

      - name: Scan Image
        uses: ./.github/actions/scan-image
        with:
          image-ref: ${{ steps.generate-image-tags.outputs.primary-name-full }}

      - name: Sign Image
        uses: ./.github/actions/sign-image
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          digest: ${{ steps.build.outputs.digest }}
          private-key: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY }}
          private-key-passphrase: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY_PASSPHRASE }}

  check:
    needs: [build-base, build-nvidia]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Check Job Status
        uses: ./.github/actions/check-jobs-success
        with:
          jobs: ${{ toJSON(needs) }}
