name: Cleanup Images

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image: [base, silverblue]

    steps:
      - name: Delete PR images
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20 # v4
        with:
          package-name: eternal-linux/main/${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 10
          # Regex to match everything except "pr*"
          ignore-versions: "^(?!pr).*$"
          token: ${{ secrets.GITHUB_TOKEN }}
