name: Build ISOs

on:
  pull_request:
    paths:
      - ".github/actions/build-iso/**"

jobs:
  build:
    uses: ./.github/workflows/_build-iso.yml
    with:
      image-name: silverblue
      image-registry: ghcr.io/rsturla/eternal-linux/main
      image-tag: 40
      flatpak-manifest-list: ./flatpaks.txt
      installer-version: 40
